export const runtime = "nodejs";

import axios from "axios";

// normalize repo input → owner/name
function extractRepoName(input) {
  let repo = input.trim();
  if (repo.includes("github.com")) repo = repo.split("github.com/")[1];
  repo = repo.replace(/^\/+|\/+$/g, "").replace(/\.git$/, "");
  return repo;
}

function slugBranchFromNextAction(next_action) {
  let slug = next_action
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!slug) slug = "change";
  slug = slug.slice(0, 40);
  return `autodevops-${slug}`;
}

function generateCI() {
  return `
name: AutoDevOps CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test || echo "No test suite defined"
`;
}

export async function POST(req) {
  try {
    const { repo, next_action } = await req.json();
    const token = process.env.GITHUB_TOKEN;

    if (!repo || !next_action) {
      return Response.json(
        { ok: false, error: "repo and next_action required" },
        { status: 400 }
      );
    }

    if (!token) {
      console.error("❌ No GITHUB_TOKEN in env");
      return Response.json(
        { ok: false, error: "Server misconfigured: missing GITHUB_TOKEN" },
        { status: 500 }
      );
    }

    const repoName = extractRepoName(repo);
    const [owner] = repoName.split("/");

    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    };

    console.log("🔧 Using repo:", repoName);
    console.log("🔧 Token length:", token.length);

    // 1) get repo default branch
    const repoInfo = await axios.get(
      `https://api.github.com/repos/${repoName}`,
      { headers }
    );
    const base = repoInfo.data.default_branch || "main";

    // 2) get base branch SHA
    const branchData = await axios.get(
      `https://api.github.com/repos/${repoName}/branches/${base}`,
      { headers }
    );
    const baseSha = branchData.data.commit.sha;

    // 3) create or reuse branch
    const branch = slugBranchFromNextAction(next_action);
    console.log("➡️ Using branch:", branch);

    try {
      await axios.post(
        `https://api.github.com/repos/${repoName}/git/refs`,
        { ref: `refs/heads/${branch}`, sha: baseSha },
        { headers }
      );
      console.log("✅ Created branch:", branch);
    } catch (err) {
      if (
        axios.isAxiosError(err) &&
        err.response?.status === 422 &&
        typeof err.response.data?.message === "string" &&
        err.response.data.message.includes("Reference already exists")
      ) {
        console.log("ℹ️ Branch already exists, continuing:", branch);
      } else {
        console.log("❌ Error creating branch:", {
          status: err.response?.status,
          data: err.response?.data,
        });
        throw err;
      }
    }

    // 4) commit CI file
    console.log(
      "➡️ Committing CI workflow to .github/workflows/ci.yml..."
    );
    try {
      await axios.put(
        `https://api.github.com/repos/${repoName}/contents/.github/workflows/ci.yml`,
        {
          message: "AutoDevOpsAI: Add CI workflow",
          content: Buffer.from(generateCI()).toString("base64"),
          branch,
        },
        { headers }
      );
      console.log("✅ CI workflow committed");
    } catch (err) {
      if (axios.isAxiosError(err) && err.response) {
        console.log("❌ Error committing CI:", {
          status: err.response.status,
          data: err.response.data,
        });
      }
      throw err;
    }

    // 5) create PR
    console.log("➡️ Creating PR...");
    let pr;
    try {
      pr = await axios.post(
        `https://api.github.com/repos/${repoName}/pulls`,
        {
          title: `🤖 AutoDevOpsAI — ${next_action}`,
          body: `This PR was auto-generated by AutoDevOps AI.`,
          head: branch,
          base,
        },
        { headers }
      );
      console.log("✅ PR created:", pr.data.html_url);
    } catch (err) {
      if (axios.isAxiosError(err) && err.response) {
        console.log("❌ Error creating PR:", {
          status: err.response.status,
          data: err.response.data,
        });
      }
      throw err;
    }

    return Response.json(
      { ok: true, pr_url: pr.data.html_url },
      { status: 200 }
    );
  } catch (err) {
    if (axios.isAxiosError(err) && err.response) {
      console.error("❌ PR create error (GitHub):", {
        status: err.response.status,
        data: err.response.data,
      });

      return Response.json(
        {
          ok: false,
          error: "Failed to create PR",
          github: err.response.data,
        },
        { status: err.response.status }
      );
    }

    console.error("❌ PR create error (unexpected):", err);
    return Response.json(
      {
        ok: false,
        error: "Failed to create PR",
        message: err.message,
      },
      { status: 500 }
    );
  }
}
