export const runtime = "nodejs";

import axios from "axios";

// normalize repo input → owner/name
function extractRepoName(input) {
  let repo = input.trim();
  if (repo.includes("github.com")) repo = repo.split("github.com/")[1];
  repo = repo.replace(/^\/+|\/+$/g, "").replace(".git", "");
  return repo;
}

function getBranchName(next_action) {
  return "autodevops-" + next_action.toLowerCase().replace(/\s+/g, "-");
}

function generateTestFile() {
  return `
// Auto-generated by AutoDevOps AI 🤖
// Basic smoke tests to ensure project setup is working.

describe("AutoDevOps smoke tests", () => {
  test("basic math sanity", () => {
    expect(2 + 2).toBe(4);
  });

  test("Node environment is available", () => {
    expect(typeof process).toBe("object");
  });
});
`;
}

export async function POST(req) {
  try {
    const { repo, token, next_action } = await req.json();

    if (!repo || !token || !next_action) {
      return Response.json(
        { ok: false, error: "repo, token & next_action required" },
        { status: 200 }
      );
    }

    const repoName = extractRepoName(repo);
    const branchName = getBranchName(next_action);
    const testPath = "tests/auto-devops.test.js";

    // 1) try to see if file already exists
    let existingSha = null;
    try {
      const existing = await axios.get(
        `https://api.github.com/repos/${repoName}/contents/${testPath}`,
        {
          headers: { Authorization: `Bearer ${token}` },
          params: { ref: branchName },
        }
      );
      existingSha = existing.data.sha;
    } catch (err) {
      // 404 is fine = file doesn't exist yet
      if (err.response?.status !== 404) {
        throw err;
      }
    }

    const fileContent = generateTestFile();

    const putBody = {
      message: "AutoDevOpsAI: Add basic test suite",
      content: Buffer.from(fileContent).toString("base64"),
      branch: branchName,
    };

    if (existingSha) {
      putBody.sha = existingSha;
    }

    const commitRes = await axios.put(
      `https://api.github.com/repos/${repoName}/contents/${testPath}`,
      putBody,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    return Response.json(
      {
        ok: true,
        file: testPath,
        branch: branchName,
        commit_url: commitRes.data.commit?.html_url || null,
      },
      { status: 200 }
    );
  } catch (err) {
    const status = err.response?.status || 500;
    const msg = err.response?.data?.message || err.message;

    console.error("❌ Auto-generate tests error:", status, msg);

    return Response.json(
      {
        ok: false,
        error: "Failed to generate tests",
        github_message: msg,
        status,
      },
      { status: 200 }
    );
  }
}
